//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.highScoresData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class highScoresData { }
#else

	public class highScoresData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public highScoresData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/WordCruncherWP7;component/SampleData/highScoresData/highScoresData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Opponent = string.Empty;

		public string Opponent
		{
			get
			{
				return this._Opponent;
			}

			set
			{
				if (this._Opponent != value)
				{
					this._Opponent = value;
					this.OnPropertyChanged("Opponent");
				}
			}
		}

		private bool _Status = false;

		public bool Status
		{
			get
			{
				return this._Status;
			}

			set
			{
				if (this._Status != value)
				{
					this._Status = value;
					this.OnPropertyChanged("Status");
				}
			}
		}

		private double _Your_Score = 0;

		public double Your_Score
		{
			get
			{
				return this._Your_Score;
			}

			set
			{
				if (this._Your_Score != value)
				{
					this._Your_Score = value;
					this.OnPropertyChanged("Your_Score");
				}
			}
		}

		private double _Their_Score = 0;

		public double Their_Score
		{
			get
			{
				return this._Their_Score;
			}

			set
			{
				if (this._Their_Score != value)
				{
					this._Their_Score = value;
					this.OnPropertyChanged("Their_Score");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
